name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Deploying Docs via Vuepress
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: stacks-task-manager/docs
        TARGET_BRANCH: deploy
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        COMMIT_MESSAGE:  Auto deploy by the Vuepress-deploy

    - uses: actions/checkout@deploy

    - name: Sync files to FTP
      uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTPSERVER }}
          user: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          local_dir: "./docs/.vuepress/dist/"
          remote_dir: "./docs.getstacksapp.com/"